export GIT_BYPASS = 0

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7A200TSBG484-3

# Define Firmware Version Number
export PRJ_VERSION = 0xEA020005

# Define the Microblaze source path
export SDK_SRC_PATH = $(PROJ_DIR)/../../common/EpixCommonGen2/src/ePix100a

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
