#export GIT_BYPASS = 0

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7A200TSBG484-3

# Firmware Version
export PRJ_VERSION = 0x00000019

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk


