
# Define target output
target: prom

# Define target part
export PRJ_PART = XC7A200TSBG484-3

export RUCKUS_DIR = $(abspath $(PWD)/../../modules/ruckus)

# Use top level makefile
include $(RUCKUS_DIR)/system_vivado.mk
