
# Define target output
target: prom

# Define target part
export PRJ_PART = XC7A200TSBG484-3

export RUCKUS_DIR = $(abspath $(PWD)/../../submodules/ruckus)

#export KEEP_UNUSED_CODE = 1

export PRJ_VERSION = 0x00000019

# Use top level makefile
include $(RUCKUS_DIR)/system_vivado.mk


