##############################################################################
## This file is part of 'EPIX Firmware'.
## It is subject to the license terms in the LICENSE.txt file found in the 
## top-level directory of this distribution and at: 
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
## No part of 'EPIX Firmware', including this file, 
## may be copied, modified, propagated, or distributed except according to 
## the terms contained in the LICENSE.txt file.
##############################################################################

#
#set_property PACKAGE_PIN AB21 [get_ports {c0_ddr4_dq[31]}]
#set_property PACKAGE_PIN W21  [get_ports {c0_ddr4_dq[30]}]
#set_property PACKAGE_PIN AB22 [get_ports {c0_ddr4_dq[29]}]
#set_property PACKAGE_PIN Y21  [get_ports {c0_ddr4_dq[28]}]
#set_property PACKAGE_PIN AA20 [get_ports {c0_ddr4_dq[27]}]
#set_property PACKAGE_PIN AA23 [get_ports {c0_ddr4_dq[26]}]
#set_property PACKAGE_PIN Y20  [get_ports {c0_ddr4_dq[25]}]
#set_property PACKAGE_PIN AA22 [get_ports {c0_ddr4_dq[24]}]
#set_property PACKAGE_PIN W26  [get_ports {c0_ddr4_dq[23]}]
#set_property PACKAGE_PIN Y26  [get_ports {c0_ddr4_dq[22]}]
#set_property PACKAGE_PIN V24  [get_ports {c0_ddr4_dq[21]}]
#set_property PACKAGE_PIN AA24 [get_ports {c0_ddr4_dq[20]}]
#set_property PACKAGE_PIN AA25 [get_ports {c0_ddr4_dq[19]}]
#set_property PACKAGE_PIN Y27  [get_ports {c0_ddr4_dq[18]}]
#set_property PACKAGE_PIN W24  [get_ports {c0_ddr4_dq[17]}]
#set_property PACKAGE_PIN V26  [get_ports {c0_ddr4_dq[16]}]
#set_property PACKAGE_PIN AC27 [get_ports {c0_ddr4_dq[15]}]
#set_property PACKAGE_PIN AB26 [get_ports {c0_ddr4_dq[14]}]
#set_property PACKAGE_PIN AD26 [get_ports {c0_ddr4_dq[13]}]
#set_property PACKAGE_PIN AC26 [get_ports {c0_ddr4_dq[12]}]
#set_property PACKAGE_PIN AD25 [get_ports {c0_ddr4_dq[11]}]
#set_property PACKAGE_PIN AB24 [get_ports {c0_ddr4_dq[10]}]
#set_property PACKAGE_PIN AB27 [get_ports {c0_ddr4_dq[9]}]
#set_property PACKAGE_PIN AB25 [get_ports {c0_ddr4_dq[8]}]
#set_property PACKAGE_PIN AH26 [get_ports {c0_ddr4_dq[7]}]
#set_property PACKAGE_PIN AF28 [get_ports {c0_ddr4_dq[6]}]
#set_property PACKAGE_PIN AG26 [get_ports {c0_ddr4_dq[5]}]
#set_property PACKAGE_PIN AE27 [get_ports {c0_ddr4_dq[4]}]
#set_property PACKAGE_PIN AF25 [get_ports {c0_ddr4_dq[3]}]
#set_property PACKAGE_PIN AE28 [get_ports {c0_ddr4_dq[2]}]
#set_property PACKAGE_PIN AG25 [get_ports {c0_ddr4_dq[1]}]
#set_property PACKAGE_PIN AF27 [get_ports {c0_ddr4_dq[0]}]
#
#set_property PACKAGE_PIN AC22 [get_ports {c0_ddr4_dm_dbi_n[3]}]
#set_property PACKAGE_PIN W25  [get_ports {c0_ddr4_dm_dbi_n[2]}]
#set_property PACKAGE_PIN AC24 [get_ports {c0_ddr4_dm_dbi_n[1]}]
#set_property PACKAGE_PIN AE25 [get_ports {c0_ddr4_dm_dbi_n[0]}]
#
#set_property PACKAGE_PIN Y22  [get_ports {c0_ddr4_dqs_t[3]}]
#set_property PACKAGE_PIN Y23  [get_ports {c0_ddr4_dqs_c[3]}]
#set_property PACKAGE_PIN W28  [get_ports {c0_ddr4_dqs_t[2]}]
#set_property PACKAGE_PIN Y28  [get_ports {c0_ddr4_dqs_c[2]}]
#set_property PACKAGE_PIN AC28 [get_ports {c0_ddr4_dqs_t[1]}]
#set_property PACKAGE_PIN AD28 [get_ports {c0_ddr4_dqs_c[1]}]
#set_property PACKAGE_PIN AG27 [get_ports {c0_ddr4_dqs_t[0]}]
#set_property PACKAGE_PIN AH27 [get_ports {c0_ddr4_dqs_c[0]}]

set_property PACKAGE_PIN AB21 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN W21  [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN AB22 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN Y21  [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN AA20 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN AA23 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN Y20  [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN AA22 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN W26  [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN Y26  [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN V24  [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN AA24 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN AA25 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN Y27  [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN W24  [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN V26  [get_ports {c0_ddr4_dq[0]}]

set_property PACKAGE_PIN AC22 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN W25  [get_ports {c0_ddr4_dm_dbi_n[0]}]

set_property PACKAGE_PIN Y22  [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN Y23  [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN W28  [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN Y28  [get_ports {c0_ddr4_dqs_c[0]}]

set_property PACKAGE_PIN P24 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN N24 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN R23 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN P23 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN N22 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN N23 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN N20 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN N21 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN M20 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN M21 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN V27 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN V28 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN U25 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN U26 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN T27 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN T28 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN R27 [get_ports {c0_ddr4_adr[16]}]

set_property PACKAGE_PIN T24 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN R28 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN T25 [get_ports {c0_ddr4_bg[0]}]

set_property PACKAGE_PIN P20  [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN P21  [get_ports {c0_ddr4_ck_c[0]}]

set_property PACKAGE_PIN V22  [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN V23  [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN U21  [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN V21  [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN V20  [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN R25  [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN R26  [get_ports c0_sys_clk_n]

