//////////////////////////////////////////////////////////////////////////////
// This file is part of 'CPIX Development Firmware'.
// It is subject to the license terms in the LICENSE.txt file found in the 
// top-level directory of this distribution and at: 
//    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
// No part of 'CPIX Development Firmware', including this file, 
// may be copied, modified, propagated, or distributed except according to 
// the terms contained in the LICENSE.txt file.
//////////////////////////////////////////////////////////////////////////////
#define BUS_OFFSET         (0x80000000)


#define ASIC0_OFFSET       (0x04000000)
#define ASIC1_OFFSET       (0x04400000)
#define ASIC2_OFFSET       (0x04800000)
#define ASIC3_OFFSET       (0x04C00000)
#define ADC_TEST_OFFSET    (0x08000000)
#define ADC0_RDO_OFFSET    (0x09000000)
#define ADC1_RDO_OFFSET    (0x09000000)
#define ADC2_RDO_OFFSET    (0x09000000)
#define ADC0_CFG_OFFSET    (0x0A000000)
#define ADC1_CFG_OFFSET    (0x0A000800)
#define ADC2_CFG_OFFSET    (0x0A001000)

#define LOG_MEM_OFFSET     (BUS_OFFSET+0x0B000000)


#define ADC0_CH0DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x00<<2))
#define ADC0_CH1DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x01<<2))
#define ADC0_CH2DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x02<<2))
#define ADC0_CH3DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x03<<2))
#define ADC0_CH4DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x04<<2))
#define ADC0_CH5DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x05<<2))
#define ADC0_CH6DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x06<<2))
#define ADC0_CH7DLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x07<<2))
#define ADC0_FRMDLY_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x20))
#define ADC0_LOCKED_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x30))
#define ADC0_FRAME_REG  (BUS_OFFSET+ADC0_RDO_OFFSET+(0x34))
#define ADC0_LCNTRST_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x38))
#define ADC0_CH0DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x20<<2))
#define ADC0_CH1DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x21<<2))
#define ADC0_CH2DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x22<<2))
#define ADC0_CH3DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x23<<2))
#define ADC0_CH4DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x24<<2))
#define ADC0_CH5DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x25<<2))
#define ADC0_CH6DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x26<<2))
#define ADC0_CH7DBG_REG (BUS_OFFSET+ADC0_RDO_OFFSET+(0x27<<2))

#define ADC1_CH0DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x00<<2))
#define ADC1_CH1DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x01<<2))
#define ADC1_CH2DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x02<<2))
#define ADC1_CH3DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x03<<2))
#define ADC1_CH4DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x04<<2))
#define ADC1_CH5DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x05<<2))
#define ADC1_CH6DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x06<<2))
#define ADC1_CH7DLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x07<<2))
#define ADC1_FRMDLY_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x20))
#define ADC1_LOCKED_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x30))
#define ADC1_FRAME_REG  (BUS_OFFSET+ADC1_RDO_OFFSET+(0x34))
#define ADC1_LCNTRST_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x38))
#define ADC1_CH0DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x20<<2))
#define ADC1_CH1DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x21<<2))
#define ADC1_CH2DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x22<<2))
#define ADC1_CH3DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x23<<2))
#define ADC1_CH4DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x24<<2))
#define ADC1_CH5DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x25<<2))
#define ADC1_CH6DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x26<<2))
#define ADC1_CH7DBG_REG (BUS_OFFSET+ADC1_RDO_OFFSET+(0x27<<2))

#define ADC2_CH0DLY_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x00<<2))
#define ADC2_CH1DLY_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x01<<2))
#define ADC2_CH2DLY_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x02<<2))
#define ADC2_CH3DLY_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x03<<2))
#define ADC2_FRMDLY_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x20))
#define ADC2_LOCKED_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x30))
#define ADC2_FRAME_REG  (BUS_OFFSET+ADC2_RDO_OFFSET+(0x34))
#define ADC2_LCNTRST_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x38))
#define ADC2_CH0DBG_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x20<<2))
#define ADC2_CH1DBG_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x21<<2))
#define ADC2_CH2DBG_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x22<<2))
#define ADC2_CH3DBG_REG (BUS_OFFSET+ADC2_RDO_OFFSET+(0x23<<2))


#define ADC0_PWRMOD_REG (BUS_OFFSET+ADC0_CFG_OFFSET+(0x8<<2))
#define ADC1_PWRMOD_REG (BUS_OFFSET+ADC1_CFG_OFFSET+(0x8<<2))
#define ADC2_PWRMOD_REG (BUS_OFFSET+ADC2_CFG_OFFSET+(0x8<<2))
#define ADC0_TSTMOD_REG (BUS_OFFSET+ADC0_CFG_OFFSET+(0xD<<2))
#define ADC1_TSTMOD_REG (BUS_OFFSET+ADC1_CFG_OFFSET+(0xD<<2))
#define ADC2_TSTMOD_REG (BUS_OFFSET+ADC2_CFG_OFFSET+(0xD<<2))
#define ADC0_OUTMOD_REG (BUS_OFFSET+ADC0_CFG_OFFSET+(0x14<<2))
#define ADC1_OUTMOD_REG (BUS_OFFSET+ADC1_CFG_OFFSET+(0x14<<2))
#define ADC2_OUTMOD_REG (BUS_OFFSET+ADC2_CFG_OFFSET+(0x14<<2))

#define ADC_TEST_CHAN_REG (BUS_OFFSET+ADC_TEST_OFFSET+(0x0<<2))
#define ADC_TEST_MASK_REG (BUS_OFFSET+ADC_TEST_OFFSET+(0x1<<2))
#define ADC_TEST_PATT_REG (BUS_OFFSET+ADC_TEST_OFFSET+(0x2<<2))
#define ADC_TEST_SMPL_REG (BUS_OFFSET+ADC_TEST_OFFSET+(0x3<<2))
#define ADC_TEST_TOUT_REG (BUS_OFFSET+ADC_TEST_OFFSET+(0x4<<2))
#define ADC_TEST_REQ_REG  (BUS_OFFSET+ADC_TEST_OFFSET+(0x5<<2))
#define ADC_TEST_PASS_REG (BUS_OFFSET+ADC_TEST_OFFSET+(0x6<<2))
#define ADC_TEST_FAIL_REG (BUS_OFFSET+ADC_TEST_OFFSET+(0x7<<2))

#define ASIC0_CFG13_REG  (BUS_OFFSET+ASIC0_OFFSET+(0x100d<<2))
#define ASIC1_CFG13_REG  (BUS_OFFSET+ASIC1_OFFSET+(0x100d<<2))
#define ASIC2_CFG13_REG  (BUS_OFFSET+ASIC2_OFFSET+(0x100d<<2))
#define ASIC3_CFG13_REG  (BUS_OFFSET+ASIC3_OFFSET+(0x100d<<2))
#define ASIC0_PREP_MULTICFG_REG  (BUS_OFFSET+ASIC0_OFFSET+(0x8000<<2))
#define ASIC1_PREP_MULTICFG_REG  (BUS_OFFSET+ASIC1_OFFSET+(0x8000<<2))
#define ASIC2_PREP_MULTICFG_REG  (BUS_OFFSET+ASIC2_OFFSET+(0x8000<<2))
#define ASIC3_PREP_MULTICFG_REG  (BUS_OFFSET+ASIC3_OFFSET+(0x8000<<2))
#define ASIC0_COL_CNT_REG        (BUS_OFFSET+ASIC0_OFFSET+(0x6013<<2))
#define ASIC1_COL_CNT_REG        (BUS_OFFSET+ASIC1_OFFSET+(0x6013<<2))
#define ASIC2_COL_CNT_REG        (BUS_OFFSET+ASIC2_OFFSET+(0x6013<<2))
#define ASIC3_COL_CNT_REG        (BUS_OFFSET+ASIC3_OFFSET+(0x6013<<2))
#define ASIC0_WR_COL_DATA_REG    (BUS_OFFSET+ASIC0_OFFSET+(0x3000<<2))
#define ASIC1_WR_COL_DATA_REG    (BUS_OFFSET+ASIC1_OFFSET+(0x3000<<2))
#define ASIC2_WR_COL_DATA_REG    (BUS_OFFSET+ASIC2_OFFSET+(0x3000<<2))
#define ASIC3_WR_COL_DATA_REG    (BUS_OFFSET+ASIC3_OFFSET+(0x3000<<2))
#define ASIC0_CMD_PREP_RD_REG    (BUS_OFFSET+ASIC0_OFFSET+(0x0000<<2))
#define ASIC1_CMD_PREP_RD_REG    (BUS_OFFSET+ASIC1_OFFSET+(0x0000<<2))
#define ASIC2_CMD_PREP_RD_REG    (BUS_OFFSET+ASIC2_OFFSET+(0x0000<<2))
#define ASIC3_CMD_PREP_RD_REG    (BUS_OFFSET+ASIC3_OFFSET+(0x0000<<2))

#define EPIX_PWR_REG       (BUS_OFFSET+0x0100020C)
#define EPIX_ASIC_MASK_REG (BUS_OFFSET+0x01000210)
#define EPIX_ADCCLK_REG    (BUS_OFFSET+0x01000300)
#define EPIX_ADC_ALIGN_REG (BUS_OFFSET+0x01000304)

unsigned int cfg13Asic[] = {ASIC0_CFG13_REG, ASIC1_CFG13_REG, ASIC2_CFG13_REG, ASIC3_CFG13_REG};
unsigned int prepMultCfgAsic[] = {ASIC0_PREP_MULTICFG_REG, ASIC1_PREP_MULTICFG_REG, ASIC2_PREP_MULTICFG_REG, ASIC3_PREP_MULTICFG_REG};
unsigned int colCntAsic[] = {ASIC0_COL_CNT_REG, ASIC1_COL_CNT_REG, ASIC2_COL_CNT_REG, ASIC3_COL_CNT_REG};
unsigned int wrColAsic[] = {ASIC0_WR_COL_DATA_REG, ASIC1_WR_COL_DATA_REG, ASIC2_WR_COL_DATA_REG, ASIC3_WR_COL_DATA_REG};
unsigned int prepRdAsic[] = {ASIC0_CMD_PREP_RD_REG, ASIC1_CMD_PREP_RD_REG, ASIC2_CMD_PREP_RD_REG, ASIC3_CMD_PREP_RD_REG};
unsigned int tstModeAdc[] = {ADC0_TSTMOD_REG, ADC1_TSTMOD_REG, ADC2_TSTMOD_REG};
unsigned int frmDlyAdc[] = {ADC0_FRMDLY_REG, ADC1_FRMDLY_REG, ADC2_FRMDLY_REG};
unsigned int frmLocAdc[] = {ADC0_LOCKED_REG, ADC1_LOCKED_REG, ADC2_LOCKED_REG};
unsigned int cntLocRstAdc[] = {ADC0_LCNTRST_REG, ADC1_LCNTRST_REG, ADC2_LCNTRST_REG};
unsigned int frameAdc[] = {ADC0_FRAME_REG, ADC1_FRAME_REG, ADC2_FRAME_REG};
unsigned int dataDlyChAdc[3][8] = {
   {ADC0_CH0DLY_REG, ADC0_CH1DLY_REG, ADC0_CH2DLY_REG, ADC0_CH3DLY_REG, ADC0_CH4DLY_REG, ADC0_CH5DLY_REG, ADC0_CH6DLY_REG, ADC0_CH7DLY_REG}, 
   {ADC1_CH0DLY_REG, ADC1_CH1DLY_REG, ADC1_CH2DLY_REG, ADC1_CH3DLY_REG, ADC1_CH4DLY_REG, ADC1_CH5DLY_REG, ADC1_CH6DLY_REG, ADC1_CH7DLY_REG}, 
   {ADC2_CH0DLY_REG, ADC2_CH1DLY_REG, ADC2_CH2DLY_REG, ADC2_CH3DLY_REG, ADC2_CH3DLY_REG, ADC2_CH3DLY_REG, ADC2_CH3DLY_REG, ADC2_CH3DLY_REG}
};
unsigned int debugAdc[3][8] = {
   {ADC0_CH0DBG_REG, ADC0_CH1DBG_REG, ADC0_CH2DBG_REG, ADC0_CH3DBG_REG, ADC0_CH4DBG_REG, ADC0_CH5DBG_REG, ADC0_CH6DBG_REG, ADC0_CH7DBG_REG}, 
   {ADC1_CH0DBG_REG, ADC1_CH1DBG_REG, ADC1_CH2DBG_REG, ADC1_CH3DBG_REG, ADC1_CH4DBG_REG, ADC1_CH5DBG_REG, ADC1_CH6DBG_REG, ADC1_CH7DBG_REG}, 
   {ADC2_CH0DBG_REG, ADC2_CH1DBG_REG, ADC2_CH2DBG_REG, ADC2_CH3DBG_REG, ADC2_CH3DBG_REG, ADC2_CH3DBG_REG, ADC2_CH3DBG_REG, ADC2_CH3DBG_REG}
};
