export GIT_BYPASS = 0

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7K325TFFG900-2

# Define Firmware Version Number
export PRJ_VERSION = 0xEA02000B

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
