export GIT_BYPASS = 1

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7A200TSBG484-3

# Define Firmware Version Number
export PRJ_VERSION = 0xAA010001

# Define the Microblaze source path                     
export SDK_SRC_PATH = $(PROJ_DIR)/../../common/EpixCommonHR/src/hr

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
