
# Define target output
target: prom

# List of build core directories.
export CORE_DIRS = $(abspath  $(PROJ_DIR)/coregen $(PROJ_DIR)/../../common/EpixCommon/coregen $(PROJ_DIR)/../../common/Pgp2Core/xil_cores )

# Max number of smart explorer runs
export SMART_MAX_RUNS = 10

# Use top level makefile
include ../../system.mk
