ePixBoard:
  enable: True
  ForceWrite: False
  dataWriter:
    enable: True
    dataFile: ''
    open: False
    bufferSize: 0
    maxFileSize: 0
  Epix10ka:
    enable: True
    EpixFpgaRegisters:
      enable: True
      RunTriggerEnable: True
      RunTriggerDelay: 0x0
      DaqTriggerEnable: True
      DaqTriggerDelay: 0x0
      DacData: 0x0
      DigitalPowerEnable: True
      AnalogPowerEnable: True
      FpgaOutputEnable: True
      IDelayCtrlRdy: 0x1
      AutoRunEnable: False
      AutoRunPeriod: 0x325aa0
      AutoDaqEnable: False
      OutPipelineDelay: 0x0
      AcqToAsicR0Delay: 0x36d0
      AsicR0ToAsicAcq: 0x2710
      AsicAcqWidth: 0x2710
      AsicAcqLToPPmatL: 0xc8
      AsicRoClkHalfT: 0x2
      AdcReadsPerPixel: 0x1
      AdcClkHalfT: 0x1
      TotalPixelsToRead: 0x8580
      AsicGR: False
      AsicAcq: False
      AsicRO: False
      AsicPpmat: True
      AsicPpbe: False
      AsicRoClk: False
      AsicPinGRControl: False
      AsicPinAcqControl: False
      AsicPinROControl: False
      AsicPinPpmatControl: True
      AsicPinPpbeControl: False
      AsicPinROClkControl: False
      AdcStreamMode: False
      AdcPatternEnable: False
      AsicR0Mode: True
      AsicR0Width: 0x1e
      AsicPPmatToReadout: 0x0
      PgpTrigEn: False
      MonStreamEn: False
      TpsTiming: 0x0
      TpsEdge: False
      RequestStartup: False
      AdcPipelineDelayA0: 0x20
      AdcPipelineDelayA1: 0x20
      AdcPipelineDelayA2: 0x20
      AdcPipelineDelayA3: 0x20
    EpixFpgaExtRegisters:
      enable: True
      GhostCorrEn: False
      DebugOut: 0x3
    Epix10kADouts:
      enable: True
      RdoutClkDelay: 0xa
      SystemClkDelay: 0x0
      RdoutOrder: 0xff0
    Oscilloscope:
      enable: True
      ArmReg: False
      TrigReg: False
      ScopeEnable: False
      TriggerEdge: Falling
      TriggerChannel: AsicRoClk
      TriggerMode: AcqStart
      TriggerAdcThresh: 0
      TriggerHoldoff: 0
      TriggerOffset: 0
      TraceLength: 50
      SkipSamples: 0
      InputChannelA: ASIC0_B2
      InputChannelB: ASIC0_B0
      TriggerDelay: 70
    Pgp2bAxi:
      enable: True
      Loopback: 'No'
      LocData: 0x0
      LocDataEn: False
      AutoStatus: False
    Epix10kaAsic0:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x3
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x3
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic1:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x3
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x3
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic2:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x3
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x3
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic3:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x3
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x3
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStartAddr: 0x0
      RowStopAddr: 0xb1
      ColStartAddr: 0x0
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    AxiVersion:
      enable: True
      ScratchPad: 0x000000
      FpgaReloadHalt: 0x0
      FpgaReloadAddress: 0x0
      UserReset: 0x0
    MicronN25Q:
      enable: True
    Ad9249Rdout[0].Adc[0]:
      enable: False
      ChannelDelay[0]: 0x0
      ChannelDelay[1]: 0x0
      ChannelDelay[2]: 0x0
      ChannelDelay[3]: 0x0
      ChannelDelay[4]: 0x0
      ChannelDelay[5]: 0x0
      ChannelDelay[6]: 0x0
      ChannelDelay[7]: 0x0
      FrameDelay: 0x0
      Invert: False
    Ad9249Rdout[0].Adc[1]:
      enable: False
      ChannelDelay[0]: 0x0
      ChannelDelay[1]: 0x0
      ChannelDelay[2]: 0x0
      ChannelDelay[3]: 0x0
      ChannelDelay[4]: 0x0
      ChannelDelay[5]: 0x0
      ChannelDelay[6]: 0x0
      ChannelDelay[7]: 0x0
      FrameDelay: 0x0
      Invert: False
    Ad9249Rdout[1].Adc[0]:
      enable: False
      ChannelDelay[0]: 0x0
      ChannelDelay[1]: 0x0
      ChannelDelay[2]: 0x0
      ChannelDelay[3]: 0x0
      FrameDelay: 0x0
      Invert: False
    Ad9249Config[0].Adc[0]:
      enable: False
      ExternalPdwnMode: Full Power Down
      InternalPdwnMode: Chip Run
      DutyCycleStabilizer: 'Off'
      ClockDivide: Divide by 1
      ChopMode: 'Off'
      DevIndexMask[7:0]: 0b0
      DevIndexMask[DCO:FCO]: 0b0
      UserTestModeCfg: single
      OutputTestMode: 'Off'
      OffsetAdjust: 0x0
      OutputInvert: False
      OutputFormat: Twos Compliment
      UserPatt1Lsb: 0x0
      UserPatt1Msb: 0x0
      UserPatt2Lsb: 0x0
      UserPatt2Msb: 0x0
      LvdsLsbFirst: False
    Ad9249Config[0].Adc[1]:
      enable: False
      ExternalPdwnMode: Full Power Down
      InternalPdwnMode: Chip Run
      DutyCycleStabilizer: 'Off'
      ClockDivide: Divide by 1
      ChopMode: 'Off'
      DevIndexMask[7:0]: 0b0
      DevIndexMask[DCO:FCO]: 0b0
      UserTestModeCfg: single
      OutputTestMode: 'Off'
      OffsetAdjust: 0x0
      OutputInvert: False
      OutputFormat: Twos Compliment
      UserPatt1Lsb: 0x0
      UserPatt1Msb: 0x0
      UserPatt2Lsb: 0x0
      UserPatt2Msb: 0x0
      LvdsLsbFirst: False
    Ad9249Config[1].Adc[0]:
      enable: False
      ExternalPdwnMode: Full Power Down
      InternalPdwnMode: Chip Run
      DutyCycleStabilizer: 'Off'
      ClockDivide: Divide by 1
      ChopMode: 'Off'
      DevIndexMask[7:0]: 0b0
      DevIndexMask[DCO:FCO]: 0b0
      UserTestModeCfg: single
      OutputTestMode: 'Off'
      OffsetAdjust: 0x0
      OutputInvert: False
      OutputFormat: Twos Compliment
      UserPatt1Lsb: 0x0
      UserPatt1Msb: 0x0
      UserPatt2Lsb: 0x0
      UserPatt2Msb: 0x0
      LvdsLsbFirst: False
    MicroblazeLog:
      enable: False
  runControl:
    enable: True
    runState: Stopped
    runRate: 1 Hz
