ePixBoard:
  enable: True
  ForceWrite: False
  dataWriter:
    enable: True
    dataFile: ''
    open: False
    bufferSize: 0
    maxFileSize: 0
  Epix10ka:
    enable: True
    EpixFpgaRegisters:
      enable: True
      RunTriggerEnable: True
      RunTriggerDelay: 0x0
      DaqTriggerEnable: True
      DaqTriggerDelay: 0x0
      DacData: 0x0
      DigitalPowerEnable: True
      AnalogPowerEnable: True
      FpgaOutputEnable: True
      IDelayCtrlRdy: 0x1
      AutoRunEnable: False
      AutoRunPeriod: 0x107d99
      AutoDaqEnable: False
      AcqToAsicR0Delay: 0x0
      AsicR0ToAsicAcq: 0x32a9
      AsicAcqWidth: 0x32a9
      AsicAcqLToPPmatL: 0xc8
      AsicRoClkT: 0x00000003
      AdcClkHalfT: 0x1
      TotalPixelsToRead: 0x8580
      AsicGR: False
      AsicAcq: False
      AsicRO: False
      AsicPpmat: True
      AsicPpbe: False
      AsicRoClk: False
      AsicPinGRControl: False
      AsicPinAcqControl: False
      AsicPinROControl: False
      AsicPinPpmatControl: True
      AsicPinPpbeControl: False
      AsicPinROClkControl: False
      AdcPatternEnable: False
      AsicR0Width: 0x1e
      AsicPPmatToReadout: 0x0
      PgpTrigEn: False
      RequestStartup: False
      AdcPipelineDelayA0: 0x1d
      AdcPipelineDelayA1: 0x1d
      AdcPipelineDelayA2: 0x1d
      AdcPipelineDelayA3: 0x1d
    EpixFpgaExtRegisters:
      enable: True
      GhostCorrEn: False
      DebugOut: 0x3
      BankPipelineDly00: 0x1d
      BankPipelineDly01: 0x1d
      BankPipelineDly02: 0x1d
      BankPipelineDly03: 0x1d
      BankPipelineDly04: 0x1d
      BankPipelineDly05: 0x1d
      BankPipelineDly06: 0x1d
      BankPipelineDly07: 0x1d
      BankPipelineDly08: 0x1d
      BankPipelineDly09: 0x1d
      BankPipelineDly10: 0x1d
      BankPipelineDly11: 0x1d
      BankPipelineDly12: 0x1d
      BankPipelineDly13: 0x1d
      BankPipelineDly14: 0x1d
      BankPipelineDly15: 0x1d
    Epix10kADouts:
      enable: True
      RdoutClkDelay: 0xa
      SystemClkDelay: 0x0
      RdoutOrder: 0xff0
    Oscilloscope:
      enable: True
      ArmReg: False
      TrigReg: False
      ScopeEnable: False
      TriggerEdge: Rising
      TriggerChannel: AsicRoClk
      TriggerMode: AcqStart
      TriggerAdcThresh: 9000
      TriggerHoldoff: 0
      TriggerOffset: 0
      TraceLength: 36
      SkipSamples: 0
      InputChannelA: ASIC1_B0
      InputChannelB: ASIC0_B0
      TriggerDelay: 2970
    Epix10kaAsic[0]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStopAddr: 0xb1
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic[1]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStopAddr: 0xb1
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic[2]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStopAddr: 0xb1
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    Epix10kaAsic[3]:
      enable: True
      CompTH_DAC: 0x22
      CompEn0: False
      CompEn1: True
      CompEn2: True
      PulserSync: False
      PixelDummy: 0x22
      Pulser: 0x0
      pbit: False
      atest: False
      test: False
      sab_test: False
      hrtest: False
      PulserR: False
      DigMon1: 0x0
      DigMon2: 0x1
      PulserDac: 0x3
      MonostPulser: 0x0
      Dm1En: False
      Dm2En: False
      emph_bd: 0x0
      emph_bc: 0x0
      VRef: 0x13
      VRefLow: 0x3
      TpsTComp: True
      TpsMux: 0x0
      RoMonost: 0x3
      TpsGr: 0x3
      S2d0Gr: 0x3
      PpOcbS2d: True
      Ocb: 0x0
      Monost: 0x3
      FastppEnable: False
      Preamp: 0x4
      PixelCb: 0x4
      Vld1_b: 0x1
      S2dTComp: False
      FilterDac: 0x11
      TestLVDTransmitter: False
      TC: 0x0
      S2d: 0x0
      S2dDacBias: 0x3
      TpsTcDac: 0x0
      TpsDac: 0x10
      S2d0TcDac: 0x1
      S2d0Dac: 0x14
      TestBe: False
      IsEn: False
      DelExec: False
      DelCckRef: False
      RO_rst_en: True
      SlvdsBit: True
      FELmode: True
      CompEnOn: False
      RowStopAddr: 0xb1
      ColStopAddr: 0x2f
      S2d1Gr: 0x3
      S2d2Gr: 0x3
      S2d3Gr: 0x3
      trbit: True
      S2d1TcDac: 0x1
      S2d1Dac: 0x12
      S2d2TcDac: 0x1
      S2d2Dac: 0x12
      S2d3TcDac: 0x1
      S2d3Dac: 0x12
    AxiVersion:
      enable: True
      ScratchPad: 0x000000
      FpgaReloadHalt: 0x0
      FpgaReloadAddress: 0x0
      UserReset: 0x0
    MicronN25Q:
      enable: True
      Test: 0x0
    MicroblazeLog:
      enable: False
  runControl:
    enable: True
    runState: Stopped
    runRate: 1 Hz
