export GIT_BYPASS = 0

# Define target output
target: vcs

# Define target part
export PRJ_PART = XC7Z045FFG900-2

# Define Firmware Version Number
export PRJ_VERSION = 0xEA020000

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
