###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Jul 22 15:10:52 2014
##  Generated by MIG Version 2.0
##  
##################################################################################################
##  File name :       ddr_controller.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-SBG484
##                    Speedgrade:        -3
##                    Design Entry:      VHDL
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J256m16XX-107
## Data Width: 32
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -name sys_clk_i -period 2.5 [get_ports sys_clk_i]
set_propagated_clock sys_clk_i
          
create_clock -name clk_ref_i -period 5 [get_ports clk_ref_i]
set_propagated_clock clk_ref_i
          